version: '3.0'

services:
  postgre:
    image: postgres:12
    restart: always
    ports:
    - 8081:5432
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASS}
      POSTGRES_DB: ${POSTGRE_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: