version: '3.0'

services:
  postgre:
    image: postgres:12
    restart: always
    ports:
    - 8081:5432
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASS}
      POSTGRES_DB: ${POSTGRE_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  journal:
    depends_on:
      - postgre
    build:
      context: .
    ports:
    - 8080:8080
    restart: always

volumes:
  db-data: