version: '3.0'

services:
  postgre:
    image: postgres:12
    restart: always
    ports:
    - 8081:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journal

  journal:
    depends_on:
      - postgre
    build:
      context: .
    ports:
    - 8080:8080