spring:
  datasource:
    initialize: true
    username: user
    password: password
    url: jdbc:postgresql://localhost:8081/journal
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql

