spring:

  main:
    lazy-initialization: true

  flyway:
    enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create


