spring:
  datasource:
    initialize: true
    username: user
    password: password
    url: jdbc:postgresql://localhost:8081/journal
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false

