spring:
  datasource:
    initialize: true
    username: user
    password: password
    url: jdbc:postgresql://localhost:8081/journal
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect

